### PR TITLE
Add HTTP auth

### PR DESCRIPTION
**Pull request by shayonj**

### CODE REVIEW

**Comment by brandonweiss** [comment]
Why are we forking this?

**Comment by shayonj** [comment]
I am not entirely sure. I believe it so that we can use our own themes https://github.com/intercom/audiogram/blob/master/settings/themes.json#L22 and probably also make it pilot compatible (to run locally). Latter reason can be achieved from other solutions.

@danielhusar thoughts? 😄

**Comment by danielhusar** [comment]
I forked it so we can easilly sync with upstream.
(Intercom specific stuff is minimal)

**Comment by brandonweiss** [comment]
I'm generally adverse to forking because syncing with upstream is tedious but if you're cool with it 👍

**Comment by danielhusar** [comment]
If you think having it as regular repo make more sense go for it :) I forked it as it really is a fork and clearly see original version make sense for me.

**Comment by brandonweiss** [comment]
No I didn't mean a normal repo vs a forked repo—that's still a fork. I meant literally forking a repo. In my experience maintaining a fork is usually a tedious pain in the ass and it's best, if possible, to get any changes merged upstream or figure out another way. But if you're comfortable maintaining it then 👍

**Comment by shayonj** [comment]
Merging this for now. I think for longer run, if this needs to scale, we'd need to come back and think of a more effective setup.

**Pull request merged**
